`--only` flag for the build-latest-rc command
salesforcecli/plugin-release-management pull request #496
Opened 2022-07-20 20:19 UTC by iowillhoit

### What does this PR do?
Allows the build-latest-rc script to *only* update the packages that are passed to the `--only` flag. This is especially useful for `patch` releases

### What issues does this PR fix or reference?
[@W-11462358@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-11462358)

2022-07-22 13:12 UTC, RodEsp requested changes
Looks good overall, just some minor comments.

2022-07-22 16:03 UTC, iowillhoit commented on src/package.ts
> +      if (value.includes(`npm:${name}`)) {
Yea, I don't think this would matter but your suggestion more explicit to someone reading the code. Thanks!

2022-07-22 16:07 UTC, RodEsp approved these changes

2022-07-22 17:00 UTC, mshanemc approved these changes
cool stuff

2022-07-25 15:20 UTC, mshanemc commented
QA notes:

❌ `sfdx cli:latestrc:build --build-only --only @salesforce/source-deploy-retrieve`
if we want to bump a library that's in resolutions but not in `dependencies`, can the command do that?  between core and sdr, I figure these might be be as common as plugin-bumps.

👎🏻  `sfdx cli:latestrc:build --build-only --only @salesforce/plugin-auth` (pick a plugin where there are no changes)
maybe tell people that there are no changes in what they specified?
bonus points: check that first and exit rather than making branches, changing versions, opening PRs.

--only salesforce-alm
✅ bumps toolbelt as expected
❓  but there aren't any other changes in other plugins/resolutions that can verify that only toolbelt will change 

🤔 probably and unrelated note: snapshot is formatted completely differently
<img width="1424" alt="Screen Shot 2022-07-25 at 10 20 04 AM" src="https://user-images.githubusercontent.com/4261788/180814729-0e8a4c45-64ff-4692-99a4-86f2193da1fd.png">

2022-07-27 20:39 UTC, iowillhoit commented on src/package.ts
> +      depInfo.finalVersion = version ?? this.getDistTags(depInfo.packageName).latest;
Just to make sure I understand what you are suggesting for the latter, change this to (pseudo): 
`finalVersion = version ?? tags['latest-rc'] ?? tags['latest']`

2022-07-29 23:33 UTC, mshanemc approved these changes

2022-08-03 16:57 UTC, mshanemc commented
qa:
✅ only on a resolutions-only will result in good message (No version changes made), as does a non-changed plugin
✅ bumps one plugin when several would normally be bumped


not tested: bumping a resolution that has changed (there are none)

2022-08-03 17:02 UTC, merged